### ISSUE TITLE
Support Jakarta package names

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-problem-java#17]
Define a strategy to support the javax to jakarta package renames (Jakarta EE > 9).

Impacts rest-problem-java-ee module (jax-rs, bean validation). For Spring integration, I don't believe there's a JEE dependency yet, until #12 is implemented.

**Comment by jpraet** [comment]
Preferably we can support Java EE and Jakarta EE side-by-side in the same version, so we don't need to keep maintain two different release branches for a long time. (so a belgif-rest-problem-jakarta-ee module that lives alongside begif-rest-problem-java-ee).

But I think this is complicated by the fact that belgif-rest-problem is not 100% decoupled from Java EE yet: some classes are annotated with Java EE annotations. This was acceptable because when these annotation classes are not found on the classpath (e.g. in Spring Boot), this does not cause any class loading issues.

These are the annotated classes:
* [Problem](https://github.com/belgif/rest-problem-java/blob/main/belgif-rest-problem/src/main/java/io/github/belgif/rest/problem/api/Problem.java) annotated with @javax.ejb.ApplicationException
* [ProblemType](https://github.com/belgif/rest-problem-java/blob/main/belgif-rest-problem/src/main/java/io/github/belgif/rest/problem/api/ProblemType.java) annotated with @javax.enterprise.inject.Stereotype

I'm not sure if it's possible to annotate these classes both with the Java EE and the equivalent Jakarta EE annotation?

For Problem, we want it to be an EJB ApplicationException to prevent it from being wrapped by the EJB container.
We could potentially work around this by implementing an exception mapper that does the unwrapping.

For ProblemType, we want it to be registered as a CDI StereoType annotation, allowing for dynamic discovery.
Supposedly, that can be done in a CDI extension with [BeforeBeanDiscovery.addStereoType()](https://jakarta.ee/specifications/cdi/2.0/apidocs/javax/enterprise/inject/spi/beforebeandiscovery#addStereotype-java.lang.Class-java.lang.annotation.Annotation...-), but I couldn't get that working so far.

**Comment by jpraet** [comment]
Spring Boot 3 requires JDK17. Does it mean belgif-rest-problem-spring would also require JDK17 if we update it to integrate with Spring Boot 3 / Jakarta? That might hinder older applications from using the library?
For CBSS it is not an issue, as we have no existing Spring Boot 2 REST APIs, and would only use it in new Spring Boot 3 apps.

**Comment by pvdbosch** [comment]
if we only add optional dependency to jakarta.validation-api 3.0 (which is compiled with JDK8) without updating the spring dependencies we could stay on older JDK; and should also be able to use the library in newer spring environments.

But if we don't have anyone from the WG requiring older Spring, it'd be easier to upgrade the module entirely to JDK17+Spring Boot 3.

**Comment by pvdbosch** [comment]
For Spring, as part of #12 , we'll work under the assumption that Spring 6 (spring boot 3) is sufficient. We can still change if a WG member wants earlier versions but that seems unlikely because Spring Boot 2 is EOL since 5 months  (at least the OSS version), and the problem library is likely to only get used for new applications.
