### ISSUE TITLE
Wrong Request method returns a 500 internal server error (Spring Boot)

### ISSUE THREAD

**Issue by smals-mavh** [belgif/rest-problem-java#38]
When calling an endpoint with the wrong request method, Spring boot throws a HttpRequestMethodNotSupportedException.
Currently this exception is not handled.

**Comment by jpraet** [comment]
What's the appropriate response to return? I guess it should be an https://www.belgif.be/specification/rest/api-guide/#http-405.

With a problem payload, or not?

https://www.belgif.be/specification/rest/api-guide/#rule-err-problem states:

> The Problem Details response body MAY be absent when the HTTP status code itself provides sufficient information (e.g. for 405 Method Not Allowed, 406 Not Acceptable or 415 Unsupported Media Type).

**Comment by pvdbosch** [comment]
Indeed a 405 without problem payload.

**Comment by jpraet** [comment]
In the same genre, we also have:

* HttpMediaTypeNotAcceptableException -> HTTP 406
* HttpMediaTypeNotSupportedException -> HTTP 415

For HTTP 406 Not Acceptable the [spec](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.6) does say:

> The server SHOULD generate a payload containing a list of available representation characteristics and corresponding resource identifiers from which the user or user agent can choose the one most appropriate.

@pvdbosch is that something we should do? Because in that case it would probably be best to return a problem payload with a new standardized problem type?

**Comment by pvdbosch** [comment]
In order to be compliant with the spec recommendations (but it's not a MUST), we could consider including a Problem payload. But I don't think its worthwhile. It doesn't seem to be [straightforward in Spring](https://www.baeldung.com/spring-httpmediatypenotacceptable) to include the supported media types in the response and probably in API Gateway neither. Client developers can still rely on the OpenAPI when debugging; it isn't a case that a client can programmatically handle.

**Comment by jpraet** [comment]
In Spring, the supported media types are available from the exception:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/HttpMediaTypeException.html#getSupportedMediaTypes()
