### ISSUE TITLE
ProblemWebClientCustomizer not compatible with Spring Boot 3

### ISSUE THREAD

**Issue by pvdbosch** [belgif/rest-problem-java#98]
We got following exception when testing with spring boot 3 webclient :

```
java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.web.reactive.function.client.ClientResponse.statusCode()'
	at io.github.belgif.rest.problem.spring.ProblemWebClientCustomizer.lambda$static$0(ProblemWebClientCustomizer.java:24) ~[belgif-rest-problem-spring-0.6.0-jakarta.jar:na]

...
```

Apparently [ClientResponse.statusCode()](https://github.com/spring-projects/spring-framework/blob/main/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/ClientResponse.java#L58) method signature changed in Spring Framework 6 from HttpStatus to HttpStatusCode, causing this error.
In Spring 6, HttpStatus has been retrofitted to implement HttpStatusCode, but even so, this seems to cause compatibility issues in  ProblemWebClientCustomizer which is compiled against Spring 5.

**Comment by jpraet** [comment]
It's a bit surprising because we have an integration test for it:

https://github.com/belgif/rest-problem-java/blob/e8f435d0ff4b11b291a12bf57507f3c85cd7b170/belgif-rest-problem-it/belgif-rest-problem-spring-boot-3-it/src/main/java/io/github/belgif/rest/problem/FrontendController.java#L103-L104

What spring boot version do you use?

**Comment by smals-mavh** [comment]
@jpraet @pvdbosch ,

We used 3.3.3, however, we had the same result with SB 3.3.1.

I've added a reproducer https://github.com/belgif/rest-problem-java/pull/100
